In [1]:
from pacce_wapper import pacce

In [2]:
a = pacce(filename='./test_table.dat', path_to_files='./test_spectra/',
         IndexDefs='./suport_files/Elham_pacce_Defs.ind',
         output_file='indicies_MILES.txt', print_log='file.txt')

In [3]:
a

,file,age,met,FWHM,z,Fe3581,Fe3619,Fe3631,Fe3646,Fe3683,...,TiO1,Ca6162,Fe6189,TiO2,TiO2sdss,CaH1,Fe6497,Halpha,Ha(Gregg94),CaH2
0,Mbi1.30Zp0.06T00.0300_iTp0.00_baseFe_linear_FW...,0.03,0.06,2.51,0.0,0.357835,0.627357,0.341245,0.194261,0.398353,...,1.519267,0.565865,0.271012,4.214053,4.513326,-0.023121,0.727915,4.176403,3.132634,3.309979
1,Mbi1.30Zp0.06T00.0400_iTp0.00_baseFe_linear_FW...,0.04,0.06,2.51,0.0,0.329218,0.689689,0.333815,0.208796,0.400020,...,1.145859,0.575623,0.272971,3.287437,3.540609,0.027931,0.788143,4.116987,3.116790,2.385394
2,Mbi1.30Zp0.06T00.0500_iTp0.00_baseFe_linear_FW...,0.05,0.06,2.51,0.0,0.277012,0.679832,0.319422,0.206109,0.358292,...,0.998435,0.578158,0.273765,2.818985,3.060624,0.058837,0.788369,4.256215,3.171779,1.615207
3,Mbi1.30Zp0.06T00.0600_iTp0.00_baseFe_linear_FW...,0.06,0.06,2.51,0.0,0.369502,0.744674,0.345381,0.228180,0.366456,...,0.916926,0.609826,0.277181,2.549453,2.793493,0.081243,0.815873,4.187222,3.124008,1.572314
4,Mbi1.30Zp0.06T00.0700_iTp0.00_baseFe_linear_FW...,0.07,0.06,2.51,0.0,0.321456,0.729037,0.324656,0.216453,0.325025,...,0.902182,0.597412,0.271081,2.334195,2.568958,0.092133,0.789114,4.282397,3.162688,1.503886
5,Mbi1.30Zp0.06T00.0800_iTp0.00_baseFe_linear_FW...,0.08,0.06,2.51,0.0,0.278104,0.714591,0.302077,0.208134,0.316779,...,0.852189,0.573203,0.257675,2.075628,2.295202,0.087735,0.745623,4.375507,3.207815,1.361464
6,Mbi1.30Zp0.06T00.0900_iTp0.00_baseFe_linear_FW...,0.09,0.06,2.51,0.0,0.268692,0.718172,0.290742,0.209289,0.330285,...,0.847660,0.555378,0.248015,2.074337,2.281246,0.076283,0.715479,4.454206,3.246027,1.360129
7,Mbi1.30Zp0.06T00.1000_iTp0.00_baseFe_linear_FW...,0.10,0.06,2.51,0.0,0.191481,0.693586,0.272317,0.196850,0.327547,...,0.826852,0.526028,0.236340,2.015409,2.205879,0.068824,0.682400,4.581702,3.313411,1.360299
8,Mbi1.30Zp0.06T00.1500_iTp0.00_baseFe_linear_FW...,0.15,0.06,2.51,0.0,0.425686,0.805384,0.326760,0.246849,0.438533,...,0.660988,0.462249,0.195892,1.464859,1.608195,0.055097,0.595062,5.137316,3.629937,1.244688
9,Mbi1.30Zp0.06T00.2000_iTp0.00_baseFe_linear_FW...,0.20,0.06,2.51,0.0,0.740131,0.945705,0.417068,0.306380,0.496960,...,0.604376,0.441278,0.184126,1.250357,1.392628,0.029042,0.547974,5.506057,3.830917,1.162697
10,Mbi1.30Zp0.06T00.2500_iTp0.00_baseFe_linear_FW...,0.25,0.06,2.51,0.0,1.090890,1.127695,0.512198,0.388536,0.498158,...,0.600584,0.445017,0.176956,1.163268,1.290462,0.036244,0.536534,5.715382,3.932290,1.069120
11,Mbi1.30Zp0.06T00.3000_iTp0.00_baseFe_linear_FW...,0.30,0.06,2.51,0.0,1.445865,1.308312,0.586276,0.457649,0.562101,...,0.576632,0.457794,0.178980,1.132982,1.240709,0.033596,0.538769,5.846663,3.999096,1.006159
12,Mbi1.30Zp0.06T00.3500_iTp0.00_baseFe_linear_FW...,0.35,0.06,2.51,0.0,1.807886,1.499621,0.679447,0.525783,0.672097,...,0.561835,0.481110,0.184746,1.103807,1.245629,0.039702,0.547693,5.827002,3.995292,0.949655
13,Mbi1.30Zp0.06T00.4000_iTp0.00_baseFe_linear_FW...,0.40,0.06,2.51,0.0,2.207686,1.789441,0.801193,0.627651,0.811641,...,0.524940,0.504149,0.193665,1.055454,1.155728,0.013594,0.575979,5.772962,3.966935,0.972522
14,Mbi1.30Zp0.06T00.4500_iTp0.00_baseFe_linear_FW...,0.45,0.06,2.51,0.0,2.386122,1.917986,0.870134,0.671540,0.859923,...,0.485099,0.526668,0.192786,1.059103,1.157366,0.026452,0.586784,5.692574,3.915287,0.980303
15,Mbi1.30Zp0.06T00.5000_iTp0.00_baseFe_linear_FW...,0.50,0.06,2.51,0.0,2.524791,2.042765,0.929415,0.712372,0.902473,...,0.470969,0.555335,0.200971,1.013277,1.106270,0.031559,0.607201,5.541200,3.848282,1.014777
16,Mbi1.30Zp0.06T00.6000_iTp0.00_baseFe_linear_FW...,0.60,0.06,2.51,0.0,3.229723,2.323959,1.110177,0.836137,1.011425,...,0.505533,0.618439,0.221642,1.080848,1.199081,0.027701,0.675576,5.213135,3.675090,0.941351
17,Mbi1.30Zp0.06T00.7000_iTp0.00_baseFe_linear_FW...,0.70,0.06,2.51,0.0,3.733885,2.595616,1.245226,0.947898,1.108085,...,0.514522,0.661157,0.238939,1.141235,1.244749,0.015625,0.721221,4.937460,3.533253,0.954105
18,Mbi1.30Zp0.06T00.8000_iTp0.00_baseFe_linear_FW...,0.80,0.06,2.51,0.0,4.154742,2.844658,1.351380,1.048912,1.178478,...,0.506922,0.717696,0.253703,1.194110,1.305413,0.017987,0.754522,4.659976,3.393684,1.064203
19,Mbi1.30Zp0.06T00.9000_iTp0.00_baseFe_linear_FW...,0.90,0.06,2.51,0.0,4.460358,3.126786,1.480004,1.160929,1.283566,...,0.554686,0.768634,0.262117,1.280999,1.409521,0.037586,0.791909,4.345287,3.222840,1.051232
20,Mbi1.30Zp0.06T01.0000_iTp0.00_baseFe_linear_FW...,1.00,0.06,2.51,0.0,4.697744,3.219216,1.591373,1.206210,1.371207,...,0.607824,0.774913,0.277388,1.403317,1.516929,0.009176,0.819331,4.034699,3.057968,1.041350
21,Mbi1.30Zp0.06T01.2500_iTp0.00_baseFe_linear_FW...,1.25,0.06,2.51,0.0,5.896835,3.627178,1.812116,1.360236,1.497970,...,0.778093,0.889595,0.343162,2.002306,2.198713,0.098335,0.924268,3.417324,2.690011,0.924529
22,Mbi1.30Zp0.06T01.5000_iTp0.00_baseFe_linear_FW...,1.50,0.06,2.51,0.0,6.204662,3.827811,1.909908,1.430352,1.542076,...,1.213725,1.022549,0.433069,3.625990,3.862339,0.129640,1.008259,3.061571,2.499363,2.659589
23,Mbi1.30Zp0.06T01.7500_iTp0.00_baseFe_linear_FW...,1.75,0.06,2.51,0.0,6.891796,4.156825,2.016521,1.539121,1.605091,...,1.261379,1.027194,0.441744,3.820667,4.035775,0.093844,1.021637,2.934826,2.427942,2.944498
24,Mbi1.30Zp0.06T02.0000_iTp0.00_baseFe_linear_FW...,2.00,0.06,2.51,0.0,7.298696,4.377324,2.101239,1.621970,1.664321,...,1.369138,1.073349,0.446445,4.081212,4.333255,0.119529,1.046865,2.792101,2.326510,3.199152
25,Mbi1.30Zp0.06T02.2500_iTp0.00_baseFe_linear_FW...,2.25,0.06,2.51,0.0,7.659610,4.533445,2.180630,1.684703,1.740844,...,1.384210,1.111956,0.450480,4.140677,4.419577,0.176824,1.056738,2.666587,2.239226,3.298672
26,Mbi1.30Zp0.06T02.5000_iTp0.00_baseFe_linear_FW...,2.50,0.06,2.51,0.0,8.152244,4.735928,2.260918,1.758768,1.818265,...,1.421749,1.139983,0.466176,4.311875,4.596039,0.197199,1.074790,2.555133,2.163807,3.473455
27,Mbi1.30Zp0.06T02.7500_iTp0.00_baseFe_linear_FW...,2.75,0.06,2.51,0.0,8.432198,4.852062,2.310668,1.802542,1.869285,...,1.474825,1.162191,0.471794,4.478057,4.775620,0.213896,1.086710,2.495543,2.132041,3.767822
28,Mbi1.30Zp0.06T03.0000_iTp0.00_baseFe_linear_FW...,3.00,0.06,2.51,0.0,8.571673,4.954019,2.340447,1.832984,1.902293,...,1.427616,1.161103,0.462944,4.269069,4.561264,0.227153,1.068484,2.500927,2.136474,3.716029
29,Mbi1.30Zp0.06T03.2500_iTp0.00_baseFe_linear_FW...,3.25,0.06,2.51,0.0,8.883619,5.089554,2.382285,1.875962,1.957688,...,1.439619,1.175248,0.468416,4.309759,4.599080,0.239492,1.073805,2.448163,2.101956,3.813385
30,Mbi1.30Zp0.06T03.5000_iTp0.00_baseFe_linear_FW...,3.50,0.06,2.51,0.0,9.111802,5.215200,2.435312,1.923981,2.002454,...,1.454155,1.192525,0.473737,4.330115,4.627001,0.254936,1.082042,2.411384,2.074794,3.783941
31,Mbi1.30Zp0.06T03.7500_iTp0.00_baseFe_linear_FW...,3.75,0.06,2.51,0.0,9.306896,5.303061,2.477849,1.965694,2.034875,...,1.461623,1.208496,0.477908,4.331002,4.637759,0.267605,1.090338,2.377884,2.052712,3.811706
32,Mbi1.30Zp0.06T04.0000_iTp0.00_baseFe_linear_FW...,4.00,0.06,2.51,0.0,9.467802,5.373346,2.511308,1.998345,2.067848,...,1.471356,1.223569,0.482209,4.387289,4.699377,0.280807,1.097462,2.332695,2.026864,3.946430
33,Mbi1.30Zp0.06T04.5000_iTp0.00_baseFe_linear_FW...,4.50,0.06,2.51,0.0,9.785346,5.500595,2.553615,2.046269,2.097746,...,1.480575,1.243472,0.485335,4.460685,4.785755,0.289296,1.107463,2.286892,2.001103,4.065192
34,Mbi1.30Zp0.06T05.0000_iTp0.00_baseFe_linear_FW...,5.00,0.06,2.51,0.0,9.802320,5.486451,2.554532,2.047233,2.126574,...,1.460951,1.245409,0.484454,4.384432,4.709903,0.294268,1.100730,2.287204,2.001646,4.098896
35,Mbi1.30Zp0.06T05.5000_iTp0.00_baseFe_linear_FW...,5.50,0.06,2.51,0.0,10.174900,5.669290,2.605472,2.112408,2.154898,...,1.471549,1.269035,0.486477,4.478085,4.820138,0.305813,1.113470,2.230931,1.972813,4.291951
36,Mbi1.30Zp0.06T06.0000_iTp0.00_baseFe_linear_FW...,6.00,0.06,2.51,0.0,10.526612,5.806293,2.649813,2.169116,2.199401,...,1.482568,1.289147,0.491911,4.541758,4.901149,0.313996,1.122556,2.191580,1.949326,4.404723
37,Mbi1.30Zp0.06T06.5000_iTp0.00_baseFe_linear_FW...,6.50,0.06,2.51,0.0,10.763937,5.878821,2.677746,2.203524,2.252344,...,1.482816,1.301984,0.494078,4.545884,4.912463,0.327754,1.125071,2.154102,1.927437,4.504384
38,Mbi1.30Zp0.06T07.0000_iTp0.00_baseFe_linear_FW...,7.00,0.06,2.51,0.0,11.012510,5.943716,2.708913,2.238350,2.308558,...,1.501645,1.315131,0.498836,4.598517,4.969044,0.337390,1.130248,2.115057,1.905231,4.631632
39,Mbi1.30Zp0.06T07.5000_iTp0.00_baseFe_linear_FW...,7.50,0.06,2.51,0.0,11.291626,6.043906,2.751947,2.280670,2.355776,...,1.513214,1.324827,0.502189,4.629296,5.007047,0.348235,1.133255,2.081028,1.888814,4.705809
40,Mbi1.30Zp0.06T08.0000_iTp0.00_baseFe_linear_FW...,8.00,0.06,2.51,0.0,11.496462,6.117977,2.782580,2.318814,2.409318,...,1.537136,1.336639,0.507039,4.671442,5.049712,0.355860,1.137634,2.044393,1.867794,4.847076
41,Mbi1.30Zp0.06T08.5000_iTp0.00_baseFe_linear_FW...,8.50,0.06,2.51,0.0,11.714563,6.192252,2.810340,2.357090,2.466755,...,1.548476,1.349672,0.512129,4.701638,5.079653,0.364511,1.142628,2.009151,1.846253,4.922254
42,Mbi1.30Zp0.06T09.0000_iTp0.00_baseFe_linear_FW...,9.00,0.06,2.51,0.0,11.895977,6.255006,2.837729,2.385948,2.504915,...,1.560645,1.361027,0.514581,4.729445,5.121403,0.377466,1.146471,1.989524,1.832656,5.026048
43,Mbi1.30Zp0.06T09.5000_iTp0.00_baseFe_linear_FW...,9.50,0.06,2.51,0.0,12.071567,6.335730,2.861615,2.416261,2.548167,...,1.569542,1.372408,0.518820,4.765809,5.166773,0.393035,1.152224,1.974522,1.818974,5.099502
44,Mbi1.30Zp0.06T10.0000_iTp0.00_baseFe_linear_FW...,10.00,0.06,2.51,0.0,12.268143,6.402529,2.881310,2.442797,2.585847,...,1.584163,1.383067,0.524735,4.840617,5.245645,0.401725,1.158689,1.952881,1.808551,5.239920
45,Mbi1.30Zp0.06T10.5000_iTp0.00_baseFe_linear_FW...,10.50,0.06,2.51,0.0,12.481642,6.476142,2.901841,2.470869,2.627704,...,1.588507,1.392987,0.527711,4.857493,5.265435,0.410897,1.161996,1.935091,1.796147,5.294805
46,Mbi1.30Zp0.06T11.0000_iTp0.00_baseFe_linear_FW...,11.00,0.06,2.51,0.0,12.560841,6.507311,2.910248,2.485394,2.655317,...,1.586008,1.406453,0.527071,4.869274,5.282267,0.421072,1.159217,1.921170,1.792184,5.387734
47,Mbi1.30Zp0.06T11.5000_iTp0.00_baseFe_linear_FW...,11.50,0.06,2.51,0.0,12.719136,6.558534,2.926361,2.507557,2.688972,...,1.589077,1.417497,0.529262,4.896741,5.314781,0.429852,1.162761,1.902920,1.780856,5.493319
48,Mbi1.30Zp0.06T12.0000_iTp0.00_baseFe_linear_FW...,12.00,0.06,2.51,0.0,12.852425,6.580970,2.937479,2.519285,2.713265,...,1.590894,1.428695,0.530677,4.918904,5.344284,0.437665,1.167740,1.885607,1.770629,5.594683
49,Mbi1.30Zp0.06T12.5000_iTp0.00_baseFe_linear_FW...,12.50,0.06,2.51,0.0,12.989715,6.610428,2.953670,2.535385,2.741107,...,1.598417,1.436652,0.532548,4.941000,5.373787,0.443795,1.173368,1.864229,1.754482,5.595890
50,Mbi1.30Zp0.06T13.0000_iTp0.00_baseFe_linear_FW...,13.00,0.06,2.51,0.0,13.195031,6.663184,2.972925,2.560691,2.777820,...,1.635041,1.445823,0.538429,5.058800,5.491410,0.446649,1.182006,1.832784,1.739356,5.727177
51,Mbi1.30Zp0.06T13.5000_iTp0.00_baseFe_linear_FW...,13.50,0.06,2.51,0.0,13.351327,6.698059,2.987845,2.577963,2.800022,...,1.642136,1.453083,0.540949,5.097277,5.530316,0.454993,1.188520,1.810125,1.726406,5.839201
52,Mbi1.30Zp0.06T14.0000_iTp0.00_baseFe_linear_FW...,14.00,0.06,2.51,0.0,13.505530,6.747001,3.007233,2.596288,2.820275,...,1.656606,1.462614,0.543122,5.120636,5.563265,0.464495,1.195175,1.805252,1.717631,5.925146

In [4]:
b = pacce(filename='./test_table.dat', path_to_files='./test_spectra/',
         IndexDefs='./suport_files/Elham_pacce_Defs.ind',
         output_file='indicies_MILES.txt', sigma_fin=300, A_to_mag=['Mg2', 'Mg1'], compute_idx='compute.txt', print_log='file.txt')

In [5]:
b

,file,age,met,FWHM,z,Fe3581,Fe3619,Fe3631,Fe3646,Fe3683,...,Fe6189,TiO2,TiO2sdss,CaH1,Fe6497,Halpha,Ha(Gregg94),CaH2,MgFe_prime,Fe_mean
0,Mbi1.30Zp0.06T00.0300_iTp0.00_baseFe_linear_FW...,0.03,0.06,2.51,0.0,-4.065448,0.375743,0.133441,0.091814,0.312306,...,0.103439,4.086756,4.397212,-0.111249,0.457342,3.904731,2.486526,3.143990,0.656593,0.787403
1,Mbi1.30Zp0.06T00.0400_iTp0.00_baseFe_linear_FW...,0.04,0.06,2.51,0.0,-4.066549,0.421699,0.110545,0.096161,0.314218,...,0.094340,3.161281,3.408426,-0.115090,0.478268,3.844416,2.473133,2.249972,0.668960,0.877901
2,Mbi1.30Zp0.06T00.0500_iTp0.00_baseFe_linear_FW...,0.05,0.06,2.51,0.0,-4.108803,0.415606,0.096148,0.089811,0.278731,...,0.086439,2.698380,2.924658,-0.105431,0.474583,3.975668,2.523435,1.478047,0.680142,0.904073
3,Mbi1.30Zp0.06T00.0600_iTp0.00_baseFe_linear_FW...,0.06,0.06,2.51,0.0,-4.024725,0.441427,0.092973,0.094732,0.285461,...,0.082364,2.425895,2.652620,-0.107498,0.490145,3.909398,2.488131,1.426767,0.719414,0.954064
4,Mbi1.30Zp0.06T00.0700_iTp0.00_baseFe_linear_FW...,0.07,0.06,2.51,0.0,-4.063020,0.434470,0.085437,0.086595,0.251695,...,0.076611,2.216586,2.437336,-0.095264,0.473473,3.999198,2.525497,1.353018,0.744367,0.945228
5,Mbi1.30Zp0.06T00.0800_iTp0.00_baseFe_linear_FW...,0.08,0.06,2.51,0.0,-4.095013,0.428175,0.072308,0.081283,0.244661,...,0.067910,1.964316,2.174498,-0.095109,0.446777,4.087451,2.568084,1.197194,0.760098,0.919894
6,Mbi1.30Zp0.06T00.0900_iTp0.00_baseFe_linear_FW...,0.09,0.06,2.51,0.0,-4.101676,0.427822,0.063405,0.082900,0.255817,...,0.061365,1.964431,2.165524,-0.102733,0.430386,4.160661,2.605048,1.191036,0.771461,0.901090
7,Mbi1.30Zp0.06T00.1000_iTp0.00_baseFe_linear_FW...,0.10,0.06,2.51,0.0,-4.171115,0.416046,0.056427,0.077341,0.253514,...,0.056092,1.906795,2.094481,-0.102395,0.410721,4.279511,2.666069,1.188368,0.759780,0.865231
8,Mbi1.30Zp0.06T00.1500_iTp0.00_baseFe_linear_FW...,0.15,0.06,2.51,0.0,-3.958942,0.481072,0.086137,0.108022,0.348793,...,0.046098,1.371296,1.508495,-0.080099,0.346373,4.800409,2.936991,1.102155,0.709122,0.748633
9,Mbi1.30Zp0.06T00.2000_iTp0.00_baseFe_linear_FW...,0.20,0.06,2.51,0.0,-3.657697,0.548650,0.113178,0.131898,0.397326,...,0.048464,1.164885,1.297399,-0.090022,0.314159,5.141152,3.111974,1.020961,0.726925,0.744037
10,Mbi1.30Zp0.06T00.2500_iTp0.00_baseFe_linear_FW...,0.25,0.06,2.51,0.0,-3.356828,0.642068,0.146974,0.173719,0.404931,...,0.048783,1.078528,1.196008,-0.073876,0.309271,5.337552,3.206332,0.917399,0.771663,0.777518
11,Mbi1.30Zp0.06T00.3000_iTp0.00_baseFe_linear_FW...,0.30,0.06,2.51,0.0,-3.046195,0.743955,0.167719,0.209693,0.456826,...,0.051489,1.049150,1.145577,-0.079171,0.309731,5.460987,3.265936,0.851010,0.802213,0.807170
12,Mbi1.30Zp0.06T00.3500_iTp0.00_baseFe_linear_FW...,0.35,0.06,2.51,0.0,-2.700031,0.851283,0.196748,0.240374,0.545449,...,0.055799,1.021385,1.143801,-0.075124,0.311210,5.443238,3.259351,0.811811,0.857968,0.856211
13,Mbi1.30Zp0.06T00.4000_iTp0.00_baseFe_linear_FW...,0.40,0.06,2.51,0.0,-2.344315,1.021297,0.239011,0.296409,0.655773,...,0.061647,0.971797,1.045413,-0.114361,0.323209,5.396756,3.232721,0.828832,0.914069,0.926464
14,Mbi1.30Zp0.06T00.4500_iTp0.00_baseFe_linear_FW...,0.45,0.06,2.51,0.0,-2.174449,1.102333,0.265391,0.315412,0.695312,...,0.058142,0.973156,1.040895,-0.112154,0.330918,5.325443,3.188324,0.840480,0.965600,0.970136
15,Mbi1.30Zp0.06T00.5000_iTp0.00_baseFe_linear_FW...,0.50,0.06,2.51,0.0,-2.049898,1.177444,0.281424,0.332145,0.733768,...,0.062159,0.923602,0.983476,-0.114937,0.343388,5.183936,3.126355,0.879355,1.015128,1.025334
16,Mbi1.30Zp0.06T00.6000_iTp0.00_baseFe_linear_FW...,0.60,0.06,2.51,0.0,-1.391289,1.327193,0.347980,0.388928,0.825687,...,0.071278,0.983634,1.062404,-0.135297,0.379687,4.877616,2.969849,0.826032,1.120760,1.173498
17,Mbi1.30Zp0.06T00.7000_iTp0.00_baseFe_linear_FW...,0.70,0.06,2.51,0.0,-0.932980,1.479140,0.397810,0.449097,0.908107,...,0.078712,1.036914,1.098434,-0.161962,0.405321,4.618756,2.844895,0.847603,1.209402,1.288464
18,Mbi1.30Zp0.06T00.8000_iTp0.00_baseFe_linear_FW...,0.80,0.06,2.51,0.0,-0.538244,1.623314,0.433368,0.503690,0.965026,...,0.084296,1.083551,1.148853,-0.179145,0.422083,4.354746,2.722990,0.962451,1.306081,1.408860
19,Mbi1.30Zp0.06T00.9000_iTp0.00_baseFe_linear_FW...,0.90,0.06,2.51,0.0,-0.219542,1.807953,0.477913,0.559541,1.047481,...,0.080906,1.170766,1.251635,-0.174308,0.447045,4.063081,2.575205,0.951494,1.404282,1.500034
20,Mbi1.30Zp0.06T01.0000_iTp0.00_baseFe_linear_FW...,1.00,0.06,2.51,0.0,0.008007,1.855020,0.536965,0.583072,1.116155,...,0.082519,1.295505,1.366962,-0.195344,0.467237,3.776162,2.431044,0.946859,1.466652,1.528451
21,Mbi1.30Zp0.06T01.2500_iTp0.00_baseFe_linear_FW...,1.25,0.06,2.51,0.0,1.133102,2.082443,0.623143,0.646210,1.221347,...,0.095050,1.882626,2.042769,-0.188175,0.539184,3.194218,2.122165,0.818721,1.711205,1.769208
22,Mbi1.30Zp0.06T01.5000_iTp0.00_baseFe_linear_FW...,1.50,0.06,2.51,0.0,1.416041,2.210819,0.653231,0.672536,1.243011,...,0.131014,3.490008,3.708581,-0.204900,0.607418,2.850230,1.971313,2.517783,1.953127,1.915132
23,Mbi1.30Zp0.06T01.7500_iTp0.00_baseFe_linear_FW...,1.75,0.06,2.51,0.0,2.053971,2.429041,0.692408,0.735017,1.290593,...,0.132416,3.681278,3.885446,-0.246186,0.618274,2.734048,1.912687,2.807521,2.046209,1.971369
24,Mbi1.30Zp0.06T02.0000_iTp0.00_baseFe_linear_FW...,2.00,0.06,2.51,0.0,2.432306,2.568298,0.727497,0.781312,1.337955,...,0.130613,3.943300,4.183762,-0.232829,0.635212,2.597644,1.831607,3.056081,2.147137,2.028636
25,Mbi1.30Zp0.06T02.2500_iTp0.00_baseFe_linear_FW...,2.25,0.06,2.51,0.0,2.774641,2.656602,0.759886,0.812407,1.399810,...,0.129177,4.003720,4.269118,-0.188699,0.640327,2.478593,1.761301,3.154492,2.221168,2.074563
26,Mbi1.30Zp0.06T02.5000_iTp0.00_baseFe_linear_FW...,2.50,0.06,2.51,0.0,3.248652,2.784545,0.799971,0.857921,1.465462,...,0.133259,4.173363,4.446295,-0.182663,0.652085,2.373446,1.702146,3.327397,2.318454,2.137950
27,Mbi1.30Zp0.06T02.7500_iTp0.00_baseFe_linear_FW...,2.75,0.06,2.51,0.0,3.521980,2.857770,0.819596,0.882336,1.506025,...,0.133793,4.337570,4.625453,-0.174016,0.660614,2.314965,1.677516,3.622814,2.380464,2.173651
28,Mbi1.30Zp0.06T03.0000_iTp0.00_baseFe_linear_FW...,3.00,0.06,2.51,0.0,3.650688,2.932352,0.836097,0.901334,1.530731,...,0.131761,4.133206,4.411567,-0.158480,0.646559,2.321546,1.679489,3.580483,2.395375,2.156959
29,Mbi1.30Zp0.06T03.2500_iTp0.00_baseFe_linear_FW...,3.25,0.06,2.51,0.0,3.944361,3.025367,0.854071,0.927232,1.575984,...,0.133403,4.172709,4.449087,-0.153926,0.649564,2.271440,1.652451,3.675392,2.449388,2.189283
30,Mbi1.30Zp0.06T03.5000_iTp0.00_baseFe_linear_FW...,3.50,0.06,2.51,0.0,4.168917,3.105842,0.876242,0.955450,1.613284,...,0.135307,4.194292,4.476997,-0.143483,0.653671,2.236793,1.630194,3.646235,2.489538,2.217014
31,Mbi1.30Zp0.06T03.7500_iTp0.00_baseFe_linear_FW...,3.75,0.06,2.51,0.0,4.362577,3.159226,0.893809,0.979868,1.641034,...,0.136481,4.196972,4.488170,-0.134648,0.658247,2.204548,1.612258,3.673431,2.526275,2.242653
32,Mbi1.30Zp0.06T04.0000_iTp0.00_baseFe_linear_FW...,4.00,0.06,2.51,0.0,4.520534,3.200771,0.908373,0.999383,1.669512,...,0.137645,4.254013,4.550587,-0.125936,0.662600,2.161611,1.591435,3.806831,2.565587,2.266411
33,Mbi1.30Zp0.06T04.5000_iTp0.00_baseFe_linear_FW...,4.50,0.06,2.51,0.0,4.827320,3.285372,0.923272,1.027708,1.691190,...,0.137731,4.327145,4.636482,-0.122247,0.669179,2.117426,1.570982,3.923664,2.624409,2.305045
34,Mbi1.30Zp0.06T05.0000_iTp0.00_baseFe_linear_FW...,5.00,0.06,2.51,0.0,4.844778,3.277512,0.929555,1.031485,1.715500,...,0.138392,4.252047,4.560091,-0.118019,0.664390,2.118548,1.571100,3.957020,2.633269,2.303632
35,Mbi1.30Zp0.06T05.5000_iTp0.00_baseFe_linear_FW...,5.50,0.06,2.51,0.0,5.212107,3.399882,0.943567,1.069914,1.737757,...,0.136459,4.344001,4.669135,-0.111154,0.673207,2.063842,1.548711,4.149578,2.701688,2.349487
36,Mbi1.30Zp0.06T06.0000_iTp0.00_baseFe_linear_FW...,6.00,0.06,2.51,0.0,5.551712,3.489710,0.959457,1.104706,1.775441,...,0.137235,4.404121,4.746792,-0.105293,0.680227,2.025099,1.530450,4.266599,2.753011,2.384089
37,Mbi1.30Zp0.06T06.5000_iTp0.00_baseFe_linear_FW...,6.50,0.06,2.51,0.0,5.783160,3.533408,0.973162,1.127978,1.819947,...,0.137239,4.406442,4.756105,-0.095149,0.681980,1.989578,1.513215,4.366990,2.788383,2.405543
38,Mbi1.30Zp0.06T07.0000_iTp0.00_baseFe_linear_FW...,7.00,0.06,2.51,0.0,6.025016,3.570085,0.989115,1.151749,1.869094,...,0.138642,4.457690,4.811746,-0.089738,0.685909,1.952463,1.495870,4.492233,2.825513,2.430150
39,Mbi1.30Zp0.06T07.5000_iTp0.00_baseFe_linear_FW...,7.50,0.06,2.51,0.0,6.305278,3.631291,1.008123,1.179581,1.910911,...,0.139538,4.488368,4.850084,-0.082391,0.687847,1.920308,1.482933,4.566577,2.862772,2.453339
40,Mbi1.30Zp0.06T08.0000_iTp0.00_baseFe_linear_FW...,8.00,0.06,2.51,0.0,6.496976,3.678450,1.024753,1.206013,1.956094,...,0.141284,4.530068,4.892414,-0.078641,0.691462,1.885401,1.466445,4.705567,2.897817,2.474265
41,Mbi1.30Zp0.06T08.5000_iTp0.00_baseFe_linear_FW...,8.50,0.06,2.51,0.0,6.703522,3.725497,1.040097,1.232829,2.003279,...,0.143065,4.559762,4.921827,-0.074644,0.694936,1.852423,1.449465,4.778175,2.931052,2.495502
42,Mbi1.30Zp0.06T09.0000_iTp0.00_baseFe_linear_FW...,9.00,0.06,2.51,0.0,6.888885,3.765162,1.052221,1.251147,2.035256,...,0.144151,4.587425,4.962778,-0.063597,0.698190,1.833678,1.438920,4.881596,2.957993,2.511436
43,Mbi1.30Zp0.06T09.5000_iTp0.00_baseFe_linear_FW...,9.50,0.06,2.51,0.0,7.060537,3.820216,1.063942,1.271425,2.073370,...,0.145818,4.623593,5.008250,-0.051750,0.703138,1.819885,1.428563,4.953062,2.988864,2.533103
44,Mbi1.30Zp0.06T10.0000_iTp0.00_baseFe_linear_FW...,10.00,0.06,2.51,0.0,7.255635,3.866201,1.074664,1.290868,2.107785,...,0.148573,4.697724,5.087825,-0.047360,0.708165,1.799250,1.420969,5.090357,3.019852,2.557020
45,Mbi1.30Zp0.06T10.5000_iTp0.00_baseFe_linear_FW...,10.50,0.06,2.51,0.0,7.466952,3.917465,1.084561,1.310155,2.143413,...,0.149750,4.714835,5.107625,-0.040994,0.710006,1.782074,1.411631,5.142412,3.039232,2.572253
46,Mbi1.30Zp0.06T11.0000_iTp0.00_baseFe_linear_FW...,11.00,0.06,2.51,0.0,7.544210,3.938719,1.089943,1.319602,2.165485,...,0.148779,4.727890,5.124098,-0.032459,0.707095,1.767771,1.408224,5.237514,3.060483,2.582141
47,Mbi1.30Zp0.06T11.5000_iTp0.00_baseFe_linear_FW...,11.50,0.06,2.51,0.0,7.698720,3.973175,1.099053,1.334807,2.194386,...,0.149140,4.755694,5.156596,-0.026471,0.709457,1.749770,1.399707,5.341571,3.084030,2.598153
48,Mbi1.30Zp0.06T12.0000_iTp0.00_baseFe_linear_FW...,12.00,0.06,2.51,0.0,7.827530,3.985350,1.105080,1.342259,2.214342,...,0.148904,4.777623,5.185138,-0.021265,0.712163,1.732226,1.392175,5.443639,3.103606,2.613783
49,Mbi1.30Zp0.06T12.5000_iTp0.00_baseFe_linear_FW...,12.50,0.06,2.51,0.0,7.959709,4.001067,1.113607,1.353570,2.236216,...,0.149009,4.799272,5.213822,-0.017834,0.715716,1.712243,1.379570,5.444831,3.127339,2.631643
50,Mbi1.30Zp0.06T13.0000_iTp0.00_baseFe_linear_FW...,13.00,0.06,2.51,0.0,8.159643,4.034016,1.123452,1.371306,2.267383,...,0.150634,4.915990,5.332055,-0.019165,0.721319,1.680550,1.368566,5.571921,3.146566,2.651710
51,Mbi1.30Zp0.06T13.5000_iTp0.00_baseFe_linear_FW...,13.50,0.06,2.51,0.0,8.308793,4.055077,1.130619,1.383371,2.285863,...,0.151307,4.953932,5.370549,-0.013620,0.725677,1.658866,1.358699,5.685170,3.161923,2.663633
52,Mbi1.30Zp0.06T14.0000_iTp0.00_baseFe_linear_FW...,14.00,0.06,2.51,0.0,8.451713,4.085547,1.137359,1.393567,2.302604,...,0.152755,4.977169,5.402958,-0.004016,0.730665,1.654139,1.352187,5.771926,3.173615,2.671039

In [5]:
c = pacce(filename='./test_table.dat', path_to_files='./test_spectra_fake_err/',IndexDefs='./suport_files/Elham_pacce_Defs.ind',simulate=10, output_file='indicies_MILES_sim.txt',
          compute_idx='compute.txt', print_log='file.txt', FWHM_fin=5.0)

In [6]:
d = pacce(filename='./test_table.dat', path_to_files='./test_spectra_fake_err/',IndexDefs='./suport_files/Elham_pacce_Defs.ind', output_file='indicies_MILES.txt',
          compute_idx='compute.txt', print_log='file.txt', FWHM_fin=5.0)

In [5]:
e = pacce(filename='./test_table.dat', path_to_files='./test_spectra_fake_err/',IndexDefs='./suport_files/Elham_pacce_Defs.ind', output_file='indicies_MILES.txt',
          compute_idx='compute.txt', print_log='file.txt', path_plots='./Pacce_figures/')

0     0.019193
1     0.024272
2     0.029926
3     0.033995
4     0.038773
5     0.042646
6     0.046417
7     0.050464
8     0.065301
9     0.079386
10    0.092363
11    0.105021
12    0.118035
13    0.130744
14    0.143403
15    0.155428
16    0.180314
17    0.204858
18    0.228277
19    0.252002
20    0.274058
21    0.304894
22    0.372530
23    0.450407
24    0.517348
25    0.576096
26    0.632688
27    0.693197
28    0.786879
29    0.835751
30    0.883831
31    0.932121
32    0.982674
33    1.079937
34    1.168877
35    1.267279
36    1.363108
37    1.466161
38    1.553890
39    1.643514
40    1.734805
41    1.827822
42    1.919938
43    2.000307
44    2.080720
45    2.160165
46    2.272210
47    2.356584
48    2.440480
49    2.514460
50    2.551588
51    2.628923
52    2.706494
Name: e_Hbeta, dtype: float64